### ISSUE TITLE
Toggle inclusion of text and graphic overrides

### ISSUE THREAD

**Issue by membranophonist** [ozgurgunes/Sketch-Symbol-States#2]
Nice plugin! It would be great to have the ability to create states that are basically combinations of visual styles, leaving any text and image overrides in place.

**Comment by ozgurgunes** [comment]
Sorry, I didn't get what you mean. Could you explain a bit more please.

**Comment by membranophonist** [comment]
I put together a mockup to (hopefully) clarify my idea.

![Symbol States plugin@2x](https://user-images.githubusercontent.com/7274867/54869673-8422e280-4d72-11e9-9ea5-9adff77baf4e.png)

**Comment by ozgurgunes** [comment]
Thanks for your labor, it clarifies enough. But I'm not sure this fits to plugins purpose. This seems like element's state rather than the symbol's. For similar situations, I prefer to make different symbols and replace them if needed. 

You can still make this by saving different states like `Akita - Default`, `Akita - Highlighted` etc.

Otherwise things getting complicated. Content and visual options are not sufficient for this situation. At least 5 checkboxes (text, symbol, text style, layer style, flow)  becomes necessary for now and may increase over time. 

I'll still think about it.

**Comment by membranophonist** [comment]
That's my usual approach as well. Problems arise when you have to adjust the position or content of all the variations of the symbol that you use as states.

I agree the configuration options could easily get out of hand. A progressive disclosure mechanism could be used if you wanted to provide that sort of granular control.

**Comment by ozgurgunes** [comment]
A nested symbol could be either content or style. I think a feature like this won't be that efficient. I'm closing this.
